name: Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # 3. Azure Login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: b3df37b5-ec4a-43df-af7e-eacb49cc0e42
          tenant-id: a7367411-ca1f-49e7-b25c-b36150bbd31a
          subscription-id: 1e97a1db-308a-4a8e-8090-ba643e150e7e

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan