name: Terraform Plan

on:
  push:
    branches:
      - feature/newrg

permissions:
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environment/dev

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

             # --------------------------------------------------
      # 3. Setup TFLint
      # --------------------------------------------------
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest


      # --------------------------------------------------
      # 4. Run TFLint
      # --------------------------------------------------
      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint


      # --------------------------------------------------
      # 5. Run Gitleaks Secret Scan
      # --------------------------------------------------
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan